services:
  - type: web
    name: planning-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - src/**
        - public/**
        - index.html
        - package.json
        - package-lock.json
        - vite.config.ts
        - tsconfig.json
        - tsconfig.node.json

  - type: web
    name: planning-server
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SMTP_HOST
        value: smtp.orange.fr
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: false
      - key: SMTP_USER
        value: mtz.trading@orange.fr
      - key: SMTP_PASS
        sync: false
